name = "amigas-cementerios"
compatibility_date = "2024-01-01"

[build]
command = "cd amigos-cementerios-react && npm run build"
cwd = "."
watch_dir = "amigos-cementerios-react/src"

[build.upload]
format = "directory"
dir = "amigos-cementerios-react/dist"

[[pages_build_output_dir]]
value = "amigos-cementerios-react/dist"