name = "amigas-cementerios"
compatibility_date = "2024-01-15"

[env.production]
account_id = "your-account-id"
zone_id = "your-zone-id"

[env.development]
compatibility_date = "2024-01-15"

# Cloudflare Pages configuration
[site]
bucket = "./dist"

[[build]]
command = "npm run build"
cwd = "."
publish = "dist"